image: docker:git
services:
  - docker:19.03.5-dind
before_script:
  - apk add --update bash coreutils tar grep
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
melodic:
  script: .industrial_ci/gitlab.sh
  variables:
    ROS_DISTRO: "melodic"
    PRERELEASE: "true"