<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="dk1"
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:arg name="robot_type" default="dk1"/>
    <xacro:arg name="is_right" default="false"/>

    <xacro:include filename="$(find senseglove_description)/urdf/dk1.ros2_control.xacro"/>
    <xacro:dk1_ros2_control robot_type="$(arg robot_type)" is_right="$(arg is_right)" />

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="joint_base_mass" value="1"/>
    <!-- arbitrary value for joint_base_mass -->
    <xacro:property name="joint_base_width" value="0.05"/>
    <!-- Cube dimensions (width x width x width) of joint base -->

    <!-- Bar lengths -->
    <xacro:property name="brake_length" value="0.0418"/>
    <xacro:property name="brake_thickness" value="0.022279"/>
    <xacro:property name="brake_height" value="0.0313"/>
    <xacro:property name="first_bar_length" value="0.026"/>
    <xacro:property name="second_bar_length" value="0.0876"/>
    <xacro:property name="third_bar_length" value="0.0664"/>


    <!-- Origins on hub for fingers -->
    <xacro:property name="thumb_hub_X" value="-0.052034"/>
    <xacro:property name="thumb_hub_Y" value="-0.0221293"/>
    <xacro:property name="thumb_hub_Z" value="0.04656"/>

    <xacro:property name="index_hub_X" value="-0.03309"/>
    <xacro:property name="index_hub_Y" value="0.00645"/>
    <xacro:property name="index_hub_Z" value="-0.04436"/>

    <xacro:property name="middle_hub_X" value="-0.011"/>
    <xacro:property name="middle_hub_Y" value="0.008"/>
    <xacro:property name="middle_hub_Z" value="-0.06222"/>

    <xacro:property name="ring_hub_X" value="0.011"/>
    <xacro:property name="ring_hub_Y" value="0.008"/>
    <xacro:property name="ring_hub_Z" value="-0.05422"/>

    <xacro:property name="pinky_hub_X" value="0.03307"/>
    <xacro:property name="pinky_hub_Y" value="0.00695"/>
    <xacro:property name="pinky_hub_Z" value="-0.04125"/>



    <xacro:property name="bar_length" value="${0.39}"/>
    <xacro:property name="bar_mass" value="1.080"/>
    <xacro:property name="bar_width" value="0.05"/>

    <xacro:property name="joint_buffer" value="${3*pi/180}"/>
    <!-- rad -->
    <xacro:property name="joint_lower_limit" value="${-8.5*pi/180}"/>
    <!-- rad -->
    <xacro:property name="joint_upper_limit" value="${8.5*pi/180}"/>
    <!-- rad -->
    <xacro:property name="joint_effort_limit" value="10927.0"/>
    <xacro:property name="joint_velocity_limit" value="1.0"/>
    <!-- rad/s -->

    <xacro:property name="hover_height" value="0.5"/>

    <!-- Used for fixing robot to Gazebo 'world' -->
    <link name="world"/>

    <!-- glove hub -->
    <link name="glove_hub">
        <visual>
            <origin xyz="-0.056692 -0.01955 -0.06803" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_HUB.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_HUB.STL" scale="0.00183889 0.0018152  0.00184029"/>
            </geometry>
            <origin xyz="-0.056692 -0.01955 -0.06803" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="50.35101166 21.72305865 48.56269594"/>
            <mass value="0.025"/>
            <inertia ixx="0.03280610139868335" ixy="0" ixz="0" iyy="0.05269840260223936" iyz="0" izz="0.025885101217440053" />
        </inertial>

    </link>

    <!-- thumb brake -->
    <link name="thumb_brake">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height/2 - 0.0025} ${-first_bar_length-second_bar_length}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Brake_assembly_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Brake_assembly_v2.STL" scale="0.00065527 0.00065208 0.00065726"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 6.67991117e-05} ${-brake_height/2 - 0.0025+ 1.65038490e-02} ${-first_bar_length-second_bar_length + 1.08450333e-01}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="11.194638649184222 31.895760000277754 128.5184426568177"/>
            <mass value="0.00481263743503889"/>
            <inertia ixx="0.0011248938907101656" ixy="0" ixz="0" iyy="0.0009310554680371946" iyz="0" izz="0.0005919770004739692" />
        </inertial>

    </link>

    <!-- thumb abduction -->
    <link name="thumb_abduction">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.006} ${-second_bar_length-first_bar_length-0.003}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Abduction_joint_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Abduction_joint_v2.STL" scale="0.00037128 0.000375   0.00037564"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 0.00322399} ${-brake_height+0.006 + 0.02010385} ${-second_bar_length-first_bar_length-0.003 + 0.10017548}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="11.201498102736423 24.557552553102166 112.63270583271043"/>
            <mass value="0.0006223548296268202"/>
            <inertia ixx="3.512006657187254e-05" ixy="0" ixz="0" iyy="4.413787180196791e-05" iyz="0" izz="1.7419595430057443e-05" />
        </inertial>


    </link>

    <!-- thumb flexion one -->
    <link name="thumb_flexion_one">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.005} ${-second_bar_length-0.0055}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Flexion_joint_1_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Flexion_joint_1_v2.STL" scale="0.00039714 0.00039916 0.00040166"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 0.00415644} ${-brake_height+0.005 + 0.02027943} ${-second_bar_length-0.0055 + 0.08129007}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="11.68858341 27.84765126 96.01288421"/>
            <mass value="0.025"/>
            <inertia ixx="0.0018502375429449178" ixy="0" ixz="0" iyy="0.0018225711056992187" iyz="0" izz="0.0008327079492581882" />
        </inertial>

    </link>

    <!-- thumb flexion two -->
    <link name="thumb_flexion_two">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.005} ${-second_bar_length-0.005355}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Flexion_joint_2_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Flexion_joint_2_v2.STL" scale="0.00139    0.00127148 0.00150504"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 4.15643978e-03} ${-brake_height+0.005 + 2.05893936e-02} ${-second_bar_length-0.005355 + 3.12924385e-07}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="27.604207234737068 29.19945517603432 38.920776706857886"/>
            <mass value="0.034526058931525355"/>
            <inertia ixx="0.02800023691993136" ixy="0" ixz="0" iyy="0.02809107932381682" iyz="0" izz="0.0010209540235572411" />
        </inertial>

    </link>

    <!-- thumb flexion three -->
    <link name="thumb_flexion_three">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.00533} -0.00533" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Flexion_joint_3_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Flexion_joint_3_v2.STL" scale="0.001      0.0011927  0.00118533"/>
            </geometry>
            <origin xyz="${-brake_thickness/2+ 0.00525644} ${-brake_height+0.00533 + 0.00561924} ${-0.00533+ 0.00015116}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="6.010029683795905 10.720012806750024 42.89809359346901"/>
            <mass value="0.004500040758898379"/>
            <inertia ixx="0.0024613506255391207" ixy="0" ixz="0" iyy="0.0022635971855287608" iyz="0" izz="0.0002727541193253326" />
        </inertial>

    </link>

    <!-- thumb thimble -->
    <link name="thumb_thimble">
        <visual>
            <origin xyz="${-brake_thickness/2} -0.014951 ${-third_bar_length-0.0028}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Thimble_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Thimble_v2.STL" scale="0.00043096 0.00043331 0.00043302"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 0.00115634} -0.014951 ${-third_bar_length-0.0028 + 0.04905724}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="10.270616342048228 11.241907236118854 66.52782703597637"/>
            <mass value="0.0009622293913480453"/>
            <inertia ixx="0.00010581465654481348" ixy="0" ixz="0" iyy="8.979368972307092e-05" iyz="0" izz="6.85624235606833e-05" />
        </inertial>

    </link>

    <!-- index brake -->
    <link name="index_brake">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height/2 - 0.0025} ${-first_bar_length-second_bar_length}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Brake_assembly_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Brake_assembly_v2.STL" scale="0.00065527 0.00065208 0.00065726"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 6.67991117e-05} ${-brake_height/2 - 0.0025+ 1.65038490e-02} ${-first_bar_length-second_bar_length + 1.08450333e-01}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="11.194638649184222 31.895760000277754 128.5184426568177"/>
            <mass value="0.00481263743503889"/>
            <inertia ixx="0.0011248938907101656" ixy="0" ixz="0" iyy="0.0009310554680371946" iyz="0" izz="0.0005919770004739692" />
        </inertial>

    </link>

    <!-- index abduction -->
    <link name="index_abduction">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.006} ${-second_bar_length-first_bar_length-0.003}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Abduction_joint_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Abduction_joint_v2.STL" scale="0.00037128 0.000375   0.00037564"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 0.00322399} ${-brake_height+0.006 + 0.02010385} ${-second_bar_length-first_bar_length-0.003 + 0.10017548}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="11.201498102736423 24.557552553102166 112.63270583271043"/>
            <mass value="0.0006223548296268202"/>
            <inertia ixx="3.512006657187254e-05" ixy="0" ixz="0" iyy="4.413787180196791e-05" iyz="0" izz="1.7419595430057443e-05" />
        </inertial>


    </link>

    <!-- index flexion one -->
    <link name="index_flexion_one">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.005} ${-second_bar_length-0.0055}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Flexion_joint_1_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Flexion_joint_1_v2.STL" scale="0.00039714 0.00039916 0.00040166"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 0.00415644} ${-brake_height+0.005 + 0.02027943} ${-second_bar_length-0.0055 + 0.08129007}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="11.68858341 27.84765126 96.01288421"/>
            <mass value="0.025"/>
            <inertia ixx="0.0018502375429449178" ixy="0" ixz="0" iyy="0.0018225711056992187" iyz="0" izz="0.0008327079492581882" />
        </inertial>



    </link>

    <!-- index flexion two -->
    <link name="index_flexion_two">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.005} ${-second_bar_length-0.005355}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Flexion_joint_2_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Flexion_joint_2_v2.STL" scale="0.00139    0.00127148 0.00150504"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 4.15643978e-03} ${-brake_height+0.005 + 2.05893936e-02} ${-second_bar_length-0.005355 + 3.12924385e-07}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="27.604207234737068 29.19945517603432 38.920776706857886"/>
            <mass value="0.034526058931525355"/>
            <inertia ixx="0.02800023691993136" ixy="0" ixz="0" iyy="0.02809107932381682" iyz="0" izz="0.0010209540235572411" />
        </inertial>

    </link>

    <!-- index flexion three -->
    <link name="index_flexion_three">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.00533} -0.00533" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Flexion_joint_3_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Flexion_joint_3_v2.STL" scale="0.001      0.0011927  0.00118533"/>
            </geometry>
            <origin xyz="${-brake_thickness/2+ 0.00525644} ${-brake_height+0.00533 + 0.00561924} ${-0.00533+ 0.00015116}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="6.010029683795905 10.720012806750024 42.89809359346901"/>
            <mass value="0.004500040758898379"/>
            <inertia ixx="0.0024613506255391207" ixy="0" ixz="0" iyy="0.0022635971855287608" iyz="0" izz="0.0002727541193253326" />
        </inertial>

    </link>

    <!-- index thimble -->
    <link name="index_thimble">
        <visual>
            <origin xyz="${-brake_thickness/2} -0.014951 ${-third_bar_length-0.0028}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Thimble_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Thimble_v2.STL" scale="0.00043096 0.00043331 0.00043302"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 0.00115634} -0.014951 ${-third_bar_length-0.0028 + 0.04905724}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="10.270616342048228 11.241907236118854 66.52782703597637"/>
            <mass value="0.0009622293913480453"/>
            <inertia ixx="0.00010581465654481348" ixy="0" ixz="0" iyy="8.979368972307092e-05" iyz="0" izz="6.85624235606833e-05" />
        </inertial>

    </link>

    <!-- middle brake -->
    <link name="middle_brake">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height/2 - 0.0025} ${-first_bar_length-second_bar_length}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Brake_assembly_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Brake_assembly_v2.STL" scale="0.00065527 0.00065208 0.00065726"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 6.67991117e-05} ${-brake_height/2 - 0.0025+ 1.65038490e-02} ${-first_bar_length-second_bar_length + 1.08450333e-01}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="11.194638649184222 31.895760000277754 128.5184426568177"/>
            <mass value="0.00481263743503889"/>
            <inertia ixx="0.0011248938907101656" ixy="0" ixz="0" iyy="0.0009310554680371946" iyz="0" izz="0.0005919770004739692" />
        </inertial>

    </link>

    <!-- middle abduction -->
    <link name="middle_abduction">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.006} ${-second_bar_length-first_bar_length-0.003}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Abduction_joint_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Abduction_joint_v2.STL" scale="0.00037128 0.000375   0.00037564"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 0.00322399} ${-brake_height+0.006 + 0.02010385} ${-second_bar_length-first_bar_length-0.003 + 0.10017548}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="11.201498102736423 24.557552553102166 112.63270583271043"/>
            <mass value="0.0006223548296268202"/>
            <inertia ixx="3.512006657187254e-05" ixy="0" ixz="0" iyy="4.413787180196791e-05" iyz="0" izz="1.7419595430057443e-05" />
        </inertial>


    </link>

    <!-- middle flexion one -->
    <link name="middle_flexion_one">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.005} ${-second_bar_length-0.0055}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Flexion_joint_1_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Flexion_joint_1_v2.STL" scale="0.00039714 0.00039916 0.00040166"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 0.00415644} ${-brake_height+0.005 + 0.02027943} ${-second_bar_length-0.0055 + 0.08129007}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="11.68858341 27.84765126 96.01288421"/>
            <mass value="0.025"/>
            <inertia ixx="0.0018502375429449178" ixy="0" ixz="0" iyy="0.0018225711056992187" iyz="0" izz="0.0008327079492581882" />
        </inertial>


    </link>

    <!-- middle flexion two -->
    <link name="middle_flexion_two">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.005} ${-second_bar_length-0.005355}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Flexion_joint_2_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Flexion_joint_2_v2.STL" scale="0.00139    0.00127148 0.00150504"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 4.15643978e-03} ${-brake_height+0.005 + 2.05893936e-02} ${-second_bar_length-0.005355 + 3.12924385e-07}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="27.604207234737068 29.19945517603432 38.920776706857886"/>
            <mass value="0.034526058931525355"/>
            <inertia ixx="0.02800023691993136" ixy="0" ixz="0" iyy="0.02809107932381682" iyz="0" izz="0.0010209540235572411" />
        </inertial>

    </link>

    <!-- middle flexion three -->
    <link name="middle_flexion_three">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.00533} -0.00533" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Flexion_joint_3_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Flexion_joint_3_v2.STL" scale="0.001      0.0011927  0.00118533"/>
            </geometry>
            <origin xyz="${-brake_thickness/2+ 0.00525644} ${-brake_height+0.00533 + 0.00561924} ${-0.00533+ 0.00015116}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="6.010029683795905 10.720012806750024 42.89809359346901"/>
            <mass value="0.004500040758898379"/>
            <inertia ixx="0.0024613506255391207" ixy="0" ixz="0" iyy="0.0022635971855287608" iyz="0" izz="0.0002727541193253326" />
        </inertial>

    </link>

    <!-- middle thimble -->
    <link name="middle_thimble">
        <visual>
            <origin xyz="${-brake_thickness/2} -0.014951 ${-third_bar_length-0.0028}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Thimble_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Thimble_v2.STL" scale="0.00043096 0.00043331 0.00043302"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 0.00115634} -0.014951 ${-third_bar_length-0.0028 + 0.04905724}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="10.270616342048228 11.241907236118854 66.52782703597637"/>
            <mass value="0.0009622293913480453"/>
            <inertia ixx="0.00010581465654481348" ixy="0" ixz="0" iyy="8.979368972307092e-05" iyz="0" izz="6.85624235606833e-05" />
        </inertial>

    </link>

    <!-- ring brake -->
    <link name="ring_brake">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height/2 - 0.0025} ${-first_bar_length-second_bar_length}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Brake_assembly_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Brake_assembly_v2.STL" scale="0.00065527 0.00065208 0.00065726"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 6.67991117e-05} ${-brake_height/2 - 0.0025+ 1.65038490e-02} ${-first_bar_length-second_bar_length + 1.08450333e-01}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="11.194638649184222 31.895760000277754 128.5184426568177"/>
            <mass value="0.00481263743503889"/>
            <inertia ixx="0.0011248938907101656" ixy="0" ixz="0" iyy="0.0009310554680371946" iyz="0" izz="0.0005919770004739692" />
        </inertial>

    </link>

    <!-- ring abduction -->
    <link name="ring_abduction">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.006} ${-second_bar_length-first_bar_length-0.003}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Abduction_joint_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Abduction_joint_v2.STL" scale="0.00037128 0.000375   0.00037564"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 0.00322399} ${-brake_height+0.006 + 0.02010385} ${-second_bar_length-first_bar_length-0.003 + 0.10017548}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="11.201498102736423 24.557552553102166 112.63270583271043"/>
            <mass value="0.0006223548296268202"/>
            <inertia ixx="3.512006657187254e-05" ixy="0" ixz="0" iyy="4.413787180196791e-05" iyz="0" izz="1.7419595430057443e-05" />
        </inertial>

    </link>

    <!-- ring flexion one -->
    <link name="ring_flexion_one">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.005} ${-second_bar_length-0.0055}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Flexion_joint_1_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Flexion_joint_1_v2.STL" scale="0.00039714 0.00039916 0.00040166"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 0.00415644} ${-brake_height+0.005 + 0.02027943} ${-second_bar_length-0.0055 + 0.08129007}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="11.68858341 27.84765126 96.01288421"/>
            <mass value="0.025"/>
            <inertia ixx="0.0018502375429449178" ixy="0" ixz="0" iyy="0.0018225711056992187" iyz="0" izz="0.0008327079492581882" />
        </inertial>


    </link>

    <!-- ring flexion two -->
    <link name="ring_flexion_two">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.005} ${-second_bar_length-0.005355}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Flexion_joint_2_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Flexion_joint_2_v2.STL" scale="0.00139    0.00127148 0.00150504"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 4.15643978e-03} ${-brake_height+0.005 + 2.05893936e-02} ${-second_bar_length-0.005355 + 3.12924385e-07}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="27.604207234737068 29.19945517603432 38.920776706857886"/>
            <mass value="0.034526058931525355"/>
            <inertia ixx="0.02800023691993136" ixy="0" ixz="0" iyy="0.02809107932381682" iyz="0" izz="0.0010209540235572411" />
        </inertial>

    </link>

    <!-- ring flexion three -->
    <link name="ring_flexion_three">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.00533} -0.00533" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Flexion_joint_3_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Flexion_joint_3_v2.STL" scale="0.001      0.0011927  0.00118533"/>
            </geometry>
            <origin xyz="${-brake_thickness/2+ 0.00525644} ${-brake_height+0.00533 + 0.00561924} ${-0.00533+ 0.00015116}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="6.010029683795905 10.720012806750024 42.89809359346901"/>
            <mass value="0.004500040758898379"/>
            <inertia ixx="0.0024613506255391207" ixy="0" ixz="0" iyy="0.0022635971855287608" iyz="0" izz="0.0002727541193253326" />
        </inertial>

    </link>

    <!-- ring thimble -->
    <link name="ring_thimble">
        <visual>
            <origin xyz="${-brake_thickness/2} -0.014951 ${-third_bar_length-0.0028}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Thimble_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Thimble_v2.STL" scale="0.00043096 0.00043331 0.00043302"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 0.00115634} -0.014951 ${-third_bar_length-0.0028 + 0.04905724}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="10.270616342048228 11.241907236118854 66.52782703597637"/>
            <mass value="0.0009622293913480453"/>
            <inertia ixx="0.00010581465654481348" ixy="0" ixz="0" iyy="8.979368972307092e-05" iyz="0" izz="6.85624235606833e-05" />
        </inertial>

    </link>

    <!-- pinky brake -->
    <link name="pinky_brake">
        <visual>
            <origin xyz="${-brake_thickness/2-0.0004} ${-brake_height/2 - 0.0025} ${-first_bar_length-second_bar_length-0.003}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Brake_assembly_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Brake_assembly_v2.STL" scale="0.00065527 0.00065208 0.00065726"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 6.67991117e-05} ${-brake_height/2 - 0.0025+ 1.65038490e-02} ${-first_bar_length-second_bar_length + 1.08450333e-01}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="11.194638649184222 31.895760000277754 128.5184426568177"/>
            <mass value="0.00481263743503889"/>
            <inertia ixx="0.0011248938907101656" ixy="0" ixz="0" iyy="0.0009310554680371946" iyz="0" izz="0.0005919770004739692" />
        </inertial>

    </link>

    <!-- pinky abduction -->
    <link name="pinky_abduction">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.006} ${-second_bar_length-first_bar_length-0.003}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Abduction_joint_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Abduction_joint_v2.STL" scale="0.00037128 0.000375   0.00037564"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 0.00322399} ${-brake_height+0.006 + 0.02010385} ${-second_bar_length-first_bar_length-0.003 + 0.10017548}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="11.201498102736423 24.557552553102166 112.63270583271043"/>
            <mass value="0.0006223548296268202"/>
            <inertia ixx="3.512006657187254e-05" ixy="0" ixz="0" iyy="4.413787180196791e-05" iyz="0" izz="1.7419595430057443e-05" />
        </inertial>


    </link>

    <!-- pinky flexion one -->
    <link name="pinky_flexion_one">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.005} ${-second_bar_length-0.0055}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Flexion_joint_1_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Flexion_joint_1_v2.STL" scale="0.00039714 0.00039916 0.00040166"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 0.00415644} ${-brake_height+0.005 + 0.02027943} ${-second_bar_length-0.0055 + 0.08129007}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="11.68858341 27.84765126 96.01288421"/>
            <mass value="0.025"/>
            <inertia ixx="0.0018502375429449178" ixy="0" ixz="0" iyy="0.0018225711056992187" iyz="0" izz="0.0008327079492581882" />
        </inertial>


    </link>

    <!-- pinky flexion two -->
    <link name="pinky_flexion_two">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.005} ${-second_bar_length-0.005355}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Flexion_joint_2_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Flexion_joint_2_v2.STL" scale="0.00139    0.00127148 0.00150504"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 4.15643978e-03} ${-brake_height+0.005 + 2.05893936e-02} ${-second_bar_length-0.005355 + 3.12924385e-07}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="27.604207234737068 29.19945517603432 38.920776706857886"/>
            <mass value="0.034526058931525355"/>
            <inertia ixx="0.02800023691993136" ixy="0" ixz="0" iyy="0.02809107932381682" iyz="0" izz="0.0010209540235572411" />
        </inertial>

    </link>

    <!-- pinky flexion three -->
    <link name="pinky_flexion_three">
        <visual>
            <origin xyz="${-brake_thickness/2} ${-brake_height+0.00533} -0.00533" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Flexion_joint_3_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Flexion_joint_3_v2.STL" scale="0.001      0.0011927  0.00118533"/>
            </geometry>
            <origin xyz="${-brake_thickness/2+ 0.00525644} ${-brake_height+0.00533 + 0.00561924} ${-0.00533+ 0.00015116}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="6.010029683795905 10.720012806750024 42.89809359346901"/>
            <mass value="0.004500040758898379"/>
            <inertia ixx="0.0024613506255391207" ixy="0" ixz="0" iyy="0.0022635971855287608" iyz="0" izz="0.0002727541193253326" />
        </inertial>

    </link>

    <!-- pinky thimble -->
    <link name="pinky_thimble">
        <visual>
            <origin xyz="${-brake_thickness/2} -0.014951 ${-third_bar_length-0.0028}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/visual/MK29_DK1_Thimble_v2.STL" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://senseglove_description/meshes/collision/MK29_DK1_Thimble_v2.STL" scale="0.00043096 0.00043331 0.00043302"/>
            </geometry>
            <origin xyz="${-brake_thickness/2 + 0.00115634} -0.014951 ${-third_bar_length-0.0028 + 0.04905724}" rpy="0 0 0"/>
        </collision>
      
        <inertial>
            <origin rpy="0 0 0" xyz="10.270616342048228 11.241907236118854 66.52782703597637"/>
            <mass value="0.0009622293913480453"/>
            <inertia ixx="0.00010581465654481348" ixy="0" ixz="0" iyy="8.979368972307092e-05" iyz="0" izz="6.85624235606833e-05" />
        </inertial>

    </link>

    <!-- Joints -->
    <joint name="joint_base_fixed_parent_joint" type="fixed">
        <parent link="world"/>
        <child link="glove_hub"/>
        <origin xyz="0 0 ${hover_height}" rpy="0 0 0"/>
    </joint>

    <joint name="hub_to_thumb_brake" type="fixed">
        <parent link="glove_hub"/>
        <child link="thumb_brake"/>
        <origin xyz="${thumb_hub_X} ${thumb_hub_Y} ${thumb_hub_Z}" rpy="${111.5*PI/180} ${40*PI/180} ${170.0*PI/180.0}"/>
    </joint>

    <joint name="thumb_brake" type="revolute">
        <parent link="thumb_brake"/>
        <child link="thumb_abduction"/>
        <origin xyz="0 0.0074 ${-0.0}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${-PI/2}" upper="${PI/2}"/>
    </joint>

    <joint name="thumb_abduction" type="fixed">
        <parent link="thumb_abduction"/>
        <child link="thumb_flexion_one"/>
        <origin xyz="0 0 ${-0.00911-0.01414}" rpy="0 0 0"/>
    </joint>

    <joint name="thumb_cmc" type="revolute">
        <parent link="thumb_flexion_one"/>
        <child link="thumb_flexion_two"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${-PI/2}" upper="${PI/2}"/>
    </joint>

    <joint name="thumb_mcp" type="revolute">
        <parent link="thumb_flexion_two"/>
        <child link="thumb_flexion_three"/>
        <origin xyz="0 0 ${-second_bar_length}" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${0}" upper="${PI/2}"/>
    </joint>

    <joint name="thumb_pip" type="revolute">
        <parent link="thumb_flexion_three"/>
        <child link="thumb_thimble"/>
        <origin xyz="0 -0.012342 ${third_bar_length-0.0025}" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${-4.2}" upper="${PI/2}"/>
    </joint>

    <joint name="hub_to_index_brake" type="fixed">
        <parent link="glove_hub"/>
        <child link="index_brake"/>
        <origin xyz="${index_hub_X} ${index_hub_Y} ${index_hub_Z}" rpy="0 0 0"/>
    </joint>

    <joint name="index_brake" type="revolute">
        <parent link="index_brake"/>
        <child link="index_abduction"/>
        <origin xyz="0 0.0074 ${-0.0}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${-PI/2}" upper="${PI/2}"/>
    </joint>

    <joint name="index_abduction" type="fixed">
        <parent link="index_abduction"/>
        <child link="index_flexion_one"/>
        <origin xyz="0 0 ${-0.00911-0.01414}" rpy="0 0 0"/>

    </joint>

    <joint name="index_mcp" type="revolute">
        <parent link="index_flexion_one"/>
        <child link="index_flexion_two"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${-PI/2}" upper="${PI/2}"/>
    </joint>

    <joint name="index_pip" type="revolute">
        <parent link="index_flexion_two"/>
        <child link="index_flexion_three"/>
        <origin xyz="0 0 ${-second_bar_length}" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${0}" upper="${PI/2}"/>
    </joint>

    <joint name="index_dip" type="revolute">
        <parent link="index_flexion_three"/>
        <child link="index_thimble"/>
        <origin xyz="0 -0.012342 ${third_bar_length-0.0025}" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${-4.2}" upper="${PI/2}"/>
    </joint>

    <joint name="hub_to_middle_brake" type="fixed">
        <parent link="glove_hub"/>
        <child link="middle_brake"/>
        <origin xyz="${middle_hub_X} ${middle_hub_Y} ${middle_hub_Z}" rpy="0 0 0"/>
    </joint>

    <joint name="middle_brake" type="revolute">
        <parent link="middle_brake"/>
        <child link="middle_abduction"/>
        <origin xyz="0 0.0074 ${-0.0}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${-PI/2}" upper="${PI/2}"/>
    </joint>

    <joint name="middle_abduction" type="fixed">
        <parent link="middle_abduction"/>
        <child link="middle_flexion_one"/>
        <origin xyz="0 0 ${-0.00911-0.01414}" rpy="0 0 0"/>
    </joint>

    <joint name="middle_mcp" type="revolute">
        <parent link="middle_flexion_one"/>
        <child link="middle_flexion_two"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${-PI/2}" upper="${PI/2}"/>
    </joint>

    <joint name="middle_pip" type="revolute">
        <parent link="middle_flexion_two"/>
        <child link="middle_flexion_three"/>
        <origin xyz="0 0 ${-second_bar_length}" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${0}" upper="${PI/2}"/>
    </joint>

    <joint name="middle_dip" type="revolute">
        <parent link="middle_flexion_three"/>
        <child link="middle_thimble"/>
        <origin xyz="0 -0.012342 ${third_bar_length-0.0025}" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${-4.2}" upper="${PI/2}"/>
    </joint>

    <joint name="hub_to_ring_brake" type="fixed">
        <parent link="glove_hub"/>
        <child link="ring_brake"/>
        <origin xyz="${ring_hub_X} ${ring_hub_Y} ${ring_hub_Z}" rpy="0 0 0"/>
    </joint>

    <joint name="ring_brake" type="revolute">
        <parent link="ring_brake"/>
        <child link="ring_abduction"/>
        <origin xyz="0 0.0074 ${-0.0}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${-PI/2}" upper="${PI/2}"/>
    </joint>

    <joint name="ring_abduction" type="fixed">
        <parent link="ring_abduction"/>
        <child link="ring_flexion_one"/>
        <origin xyz="0 0 ${-0.00911-0.01414}" rpy="0 0 0"/>

    </joint>

    <joint name="ring_mcp" type="revolute">
        <parent link="ring_flexion_one"/>
        <child link="ring_flexion_two"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${-PI/2}" upper="${PI/2}"/>
    </joint>

    <joint name="ring_pip" type="revolute">
        <parent link="ring_flexion_two"/>
        <child link="ring_flexion_three"/>
        <origin xyz="0 0 ${-second_bar_length}" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${0}" upper="${PI/2}"/>
    </joint>

    <joint name="ring_dip" type="revolute">
        <parent link="ring_flexion_three"/>
        <child link="ring_thimble"/>
        <origin xyz="0 -0.012342 ${third_bar_length-0.0025}" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${-4.2}" upper="${PI/2}"/>
    </joint>

    <joint name="hub_to_pinky_brake" type="fixed">
        <parent link="glove_hub"/>
        <child link="pinky_brake"/>
        <origin xyz="${pinky_hub_X} ${pinky_hub_Y} ${pinky_hub_Z}" rpy="0 0 0"/>
    </joint>

    <joint name="pinky_brake" type="revolute">
        <parent link="pinky_brake"/>
        <child link="pinky_abduction"/>
        <origin xyz="0 0.0074 ${-0.0}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${-PI/2}" upper="${PI/2}"/>
    </joint>

    <joint name="pinky_abduction" type="fixed">
        <parent link="pinky_abduction"/>
        <child link="pinky_flexion_one"/>
        <origin xyz="0 0 ${-0.00911-0.01414}" rpy="0 0 0"/>
    </joint>

    <joint name="pinky_mcp" type="revolute">
        <parent link="pinky_flexion_one"/>
        <child link="pinky_flexion_two"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${-PI/2}" upper="${PI/2}"/>
    </joint>

    <joint name="pinky_pip" type="revolute">
        <parent link="pinky_flexion_two"/>
        <child link="pinky_flexion_three"/>
        <origin xyz="0 0 ${-second_bar_length}" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${0}" upper="${PI/2}"/>
    </joint>

    <joint name="pinky_dip" type="revolute">
        <parent link="pinky_flexion_three"/>
        <child link="pinky_thimble"/>
        <origin xyz="0 -0.012342 ${third_bar_length-0.0025}" rpy="0 0 0"/>
        <axis xyz="-1 0 0"/>

        <limit velocity="${1000}" effort="${100}" lower="${-4.2}" upper="${PI/2}"/>
    </joint>
</robot>
